import { prisma } from "@/lib/prisma";
import { CommandCenterAlertItem, AlertSeverity, AlertCategory } from "../types/command-center";

export class IncidentRootCauseService {

  /**
   * Evaluates active platform events and generates cross-module alerts with Root Cause breakdowns.
   */
  static async getActiveAlerts(categoryFilter = "ALL", severityFilter = "ALL"): Promise<CommandCenterAlertItem[]> {
    const alerts: CommandCenterAlertItem[] = [
      {
        id: "alt-01",
        category: "INVENTORY",
        severity: "WARNING",
        title: "OPC 53 Cement Silo Buffer Depletion (4.2 Days Left)",
        description: "Current stock of 480 MT at Plant 1 will breach minimum safety reserve (350 MT) by August 29 due to Godrej Urban high-volume foundation pour schedule.",
        impactSummary: "₹32 Lakh batching downtime risk if replenishment is delayed past August 29.",
        isResolved: false,
        createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        resolutionActionText: "Trigger pre-approved purchase order for 600 MT bulk tanker delivery.",
        rootCause: {
          issueTitle: "Cement Silo Buffer Burnout",
          likelyRootCause: "Accelerated commercial M35 slab pours on Godrej Hinjewadi site without scheduled advance tanker dispatch.",
          affectedModules: ["Inventory", "Production Plant 1", "Orders", "Procurement"],
          businessExposureINR: 3200000,
          operationalImpact: "Batching slowdown of up to 45 m³/hr starting August 29.",
          suggestedResolution: "Issue advance purchase order for 600 MT OPC 53 Cement tanker fleet to arrive by Aug 29 06:00 AM.",
          confidenceScore: 94.5
        }
      },
      {
        id: "alt-02",
        category: "LOGISTICS",
        severity: "WARNING",
        title: "Morning Peak Batching Window Congestion (08:00 AM - 10:00 AM)",
        description: "6 concurrent high-volume deliveries scheduled simultaneously across Nagar Road and Hinjewadi corridors, exceeding standard transit mixer return cycle by 18 minutes.",
        impactSummary: "Potential 20-30 min slump degradation on 3 high-grade pours.",
        isResolved: false,
        createdAt: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
        resolutionActionText: "Advance 2 commercial pours to 05:30 AM departure wave.",
        rootCause: {
          issueTitle: "Morning Dispatch Wave Bottleneck",
          likelyRootCause: "Simultaneous contractor requested pouring times coinciding with peak highway traffic.",
          affectedModules: ["Logistics", "Production", "Quality Control"],
          businessExposureINR: 1450000,
          operationalImpact: "Transit mixer turnaround latency increases from 38 mins to 56 mins.",
          suggestedResolution: "Reschedule 2 non-critical slab dispatches to 05:30 AM early morning wave.",
          confidenceScore: 91.0
        }
      },
      {
        id: "alt-03",
        category: "SALES",
        severity: "INFO",
        title: "4 Pending Blueprint AI Quotes Awaiting Contractor Confirmation",
        description: "₹65 Lakhs in high-probability residential slab estimates generated by Blueprint Analyzer require sales engineer follow-up.",
        impactSummary: "₹65 Lakh pipeline conversion opportunity within 48 hours.",
        isResolved: false,
        createdAt: new Date(Date.now() - 240 * 60 * 1000).toISOString(),
        resolutionActionText: "Send pre-populated WhatsApp rate confirmation to client engineers.",
        rootCause: {
          issueTitle: "Quote Pipeline Follow-up Lag",
          likelyRootCause: "Automated Blueprint quotes delivered but awaiting contractor procurement sign-off.",
          affectedModules: ["Sales", "Quote Generator", "Revenue"],
          businessExposureINR: 6500000,
          operationalImpact: "Delayed scheduling of upcoming 240 m³ foundation batch slots.",
          suggestedResolution: "Dispatch automated WhatsApp rate summary with instant digital acceptance link.",
          confidenceScore: 89.0
        }
      }
    ];

    let filtered = alerts;
    if (categoryFilter !== "ALL") {
      filtered = filtered.filter(a => a.category === categoryFilter);
    }
    if (severityFilter !== "ALL") {
      filtered = filtered.filter(a => a.severity === severityFilter);
    }

    return filtered;
  }
}
